### ISSUE TITLE
Demo Repo

### ISSUE THREAD

**Issue by tacman** [FabienPapet/stripe-bundle#14]
### Describe the solution you'd like

I'd love to have a demo repo that shows off this bundle.

That is, download the demo, get a stripe API key, add a product, edit a product, add a customer, order a product, etc.

I can help with some PR's once a basic structure is in place. 

I think this is the _only_ stripe bundle compatible with Symfony 7!

### Do you plan to work on this feature?

- [ ] I'm willing to submit a Pull Request that implements this feature.

**Comment by FabienPapet** [comment]
Hey 👋 Thank you for your interest in this bundle. 


I like the idea of the demo project, but now, this bundle is only about handling stripe webhooks as symfony events. 

Adding all of these features can be a lot of work, but do not hesitate to open a PR if you can help. 

I'd gladly review it !

**Comment by tacman** [comment]
Ah, maybe consider renaming the bundle and tweaking the description and README?  Indeed, I was hoping to find a wrapper for the API calls, it's a huge task!

**Comment by FabienPapet** [comment]
As said, for now, it is only webhook to symfony events tool, as this covers my needs and I don't have time to add more features. 

This bundle is meant to have a stripe integration, so I won't rename the bundle. If there's a feature that you need, feel free to contribute.

edit: see the next steps part of the readme for the future plans
