### ISSUE TITLE
upgrade to v14

### ISSUE THREAD

**Issue by haivala** [FabienPapet/stripe-bundle#15]
### Describe the solution you'd like

Thank you for awesome bundle!
Any chance to get upgrade to stripe v14?

### Do you plan to work on this feature?

- [ ] I'm willing to submit a Pull Request that implements this feature.

**Comment by FabienPapet** [comment]
Hello, thank you for the feedback. I cannot work on this ATM. But if you make a PR I'd happily review it.

**Comment by haivala** [comment]
Thank you!
